#specify the version of docker-compose
version: "3.8"

# add the services needed (postgres.go)

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: loan-app-db
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  
  go:
    container_name: go
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - "postgres"

volumes:
  dbdata: